config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :projects
  resources :reviews
  resources :products
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
#  devise_for :users, controllers: {
#    sessions: "users/sessions",
#    registrations: 'users/registrations'
#  }
  resources :users, only: [:index, :show]
  resources :homes, only: [:index]
  root to: "tops#index"
  post '/tops/guest_sign_in', to: 'tops#guest_sign_in'
  resources :documents
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :filepath, DocumentUploader
  belongs_to :product
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include ActionController::Streaming
  include Zipline
  before_action :set_document, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[new edit update destroy]

  # GET /documents or /documents.json
  def index
    products = Product.all
    @product_choice = []
    products.each do |product|
      @product_choice << [product.name, product.id]
    end

#    @documents = Document.all
    @q = Document.ransack(params[:q])
    @documents = @q.result(distinct: true)

    respond_to do |format|
      format.html
      format.zip do
#        byebug
        files =  @documents.where.not(filepath: nil).map{ |document| [document.filepath, "#{document.title}.pdf"] }
        zipline(files, 'documents.zip')
      end
    end
  end

  # GET /documents/1 or /documents/1.json
  def show
#    byebug
  end

  # GET /documents/new
  def new
    @document = Document.new
    products = Product.all
    @product_choice = []
    products.each do |product|
      @product_choice << [product.name, product.id]
    end
  end

  # GET /documents/1/edit
  def edit
    products = Product.all
    @product_choice = []
    products.each do |product|
      @product_choice << [product.name, product.id]
    end
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)
#    byebug
    @document.product_id = document_params[:product_id] #入力時に選択した製品のidを、documentの外部 key として記録
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    @document.product_id = document_params[:product_id] #入力時に選択した製品のidを、documentの外部 key として記録
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:title, :content, :product_id, :filepath, :category, :control_number, :authorize)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.select :product_id, @product_choice %>
  </div>

  <div class="field">
    <%= form.label :filepath %>
    <%= form.file_field :filepath %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, [["その他文書", 0],["ビジネスプラン", 1]], include_blank: "選択してください" %>
  </div>

  <div class="field">
    <%= form.label :authorize %>
    <%= form.select :authorize, [["未承認", false],["承認", true]], include_blank: "選択してください" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<% if current_user.admin == true %>
  <h1>Documents_admin</h1>
<% else %>
  <h1>Documents</h1>
<% end %>

<%= search_form_for @q do |f| %>
  <%= f.label :title, "Keyword" %>
  <%= f.search_field :title_cont %>

  <%= f.label :product_id, "対象製品" %>
  <%= f.select :product_id_eq, @product_choice, {include_blank: '選択なし'} %>

  <%= f.label :category, "文書タイプ" %>
  <%= f.select :category_eq, [[0, 0], [1, 1]], {include_blank: '選択なし'} %>

  <%= f.submit "検索" %>
<% end %>

<%= link_to '一括ダウンロード', documents_path(format: :zip) %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>対象製品</th>
      <th>Category</th>
      <th>Authorize</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= document.content %></td>
        <td><%= document.product.name %></td>
        <td><%= document.category %></td>
        <td><%= document.authorize %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p>
  <strong>タイトル:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>コンテンツ:</strong>
  <%= @document.content %>
</p>

<p>
  <strong>対象製品:</strong>
  <%= @document.product.name %>
</p>

<p>
  <strong>ファイル:</strong>
  <%= link_to @document.filepath, @document.filepath.url %>
<!--  <a href="/Users/o541/workspace/original_app_test/public/uploads/document/filepath/2/test.pdf">リンク</a> -->
</p>

<p>
  <strong>ファイル種別:</strong>
  <%= @document.category %>
</p>

<p>
  <strong>承認:</strong>
  <%= @document.authorize %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>